language: php

dist: trusty

addons:
  postgresql: "9.2"

services:
  - postgresql
  - mysql

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

before_install:
  - if [[ ${TRAVIS_PHP_VERSION} != "7.4snapshot" ]]; then phpenv config-rm xdebug.ini; fi

before_script:
    - if [[ $PREFER_LOWEST != 1 ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
    - if [[ $PREFER_LOWEST == 1 ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi
    - if [[ $DEFAULT = 1 ]]; then mysql -e 'create database phinx_testing;'; fi
    - if [[ $DEFAULT = 1 ]]; then psql -c 'create database phinx_testing;' -U postgres; fi
    - if [[ $DEFAULT = 1 ]]; then psql -c 'create extension if not exists citext;' -U postgres; fi

    - if [[ $PHPCS = 1 ]]; then composer require --dev squizlabs/php_codesniffer:^3.1.1; fi
    - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.9; fi

script:
    - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
    - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -c phpstan.neon -l 4 src/; fi
    - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p -s src/; fi

after_success:
  - if [[ $DEFAULT = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false
